<?php
/*
 *     Block Guide
 *    Magento menu: $block->getChildHtml('store.menu');
 *    Language: $block->getChildHtml('store_language');
 *    Currency: $block->getChildHtml('currency');
 *    Top Links: $block->getChildHtml('top.links');
 *    Skip Content Block: $block->getChildHtml('skip_to_content');
 *    Logo: $block->getChildHtml('logo');
 *    Mini Cart: $block->getChildHtml('minicart');
 *    Search: $block->getChildHtml('topSearch');
 *    Static block: $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('your_block_identifier')->toHtml();
 */
?>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 * @var \Magento\Framework\Escaper $escaper
 */
$welcomeMessage = $block->getWelcome();
?>
<?php

$host = $_SERVER['HTTP_HOST'];


if (!isset($_COOKIE) || !isset($_COOKIE['browserlanguage']) && !isset($_GET["lp"])) {
   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $store = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
   $code = substr($store->getStore()->getCode(), 0, 2);
   if (isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
      $lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);
   } else {
      $lang = 'en';
   }

   $acceptLang = ['de', 'it', 'en'];
   $lang = in_array($lang, $acceptLang) ? $lang : 'en';
   setcookie("browserlanguage", $lang);
   $uri = $_SERVER['REQUEST_URI'];
   if ($lang != $code && !strpos($uri, '_toscana')) {
      header("HTTP/1.1 301 Moved Permanently");
      header("Location: https://" . $host . "/" . $lang . "/");
      exit();
   }
}

if ($block->getShowPart() == 'welcome') : ?>
    <li class="greet welcome" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <span class="logged-in"
              data-bind="text: new String('<?= $escaper->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
        </span>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <span class="not-logged-in"
              data-bind="html: '<?= $escaper->escapeHtmlAttr($welcomeMessage) ?>'"></span>
        <?= $block->getBlockHtml('header.additional') ?>
        <!-- /ko -->
    </li>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif ?>